#!/bin/bash

clear

display_mode=1

for mapId in {0..8}; do
	echo "Arena: $mapId"
    for initPos in True False; do
        python3.9 tetracomposibot.py config_Paintwars "$mapId" "$initPos" "$display_mode"
    done
done
